#!/bin/bash
#$ -S /bin/bash
#$ -V
#$ -cwd
#$ -M pauline.auffret@ifremer.fr
#$ -m bea
#$ -q long.q@@bignode
#$ -pe thread 24
#$ -e /projet/externe/ifremer/pauffret/pinctada_transcriptome_assembly/archives/log/assembly_trinity_PE_norm_10samples
#$ -o /projet/externe/ifremer/pauffret/pinctada_transcriptome_assembly/archives/log/assembly_trinity_PE_norm_10samples

#Global variables
WORKING_DIRECTORY=/scratch/externe/ifremer/pauffret/pinctada_transcriptome_assembly/results/assembly_trinity_norm_10samples_011017
DATA_DIR=/scratch/externe/ifremer/pauffret/pinctada_transcriptome_assembly/results/trimming_trimmomatic_011017/paired

#Trinity variables
TRINITY_EXEC=/usr/local/genome2/trinityrnaseq-2.4.0/Trinity 
VERSION="2.4.0"
SEQ_TYPE="fq"	#fastq input files
LEFT="${DATA_DIR}/HI.4112.001.D707---D506.X4/HI.4112.001.D707---D506.X4_R1_paired.fastq.gz,${DATA_DIR}/HI.4112.001.D707---D507.X6/HI.4112.001.D707---D507.X6_R1_paired.fastq.gz,${DATA_DIR}/HI.4112.001.D708---D504.X13/HI.4112.001.D708---D504.X13_R1_paired.fastq.gz,${DATA_DIR}/HI.4112.002.D710---D502.X19/HI.4112.002.D710---D502.X19_R1_paired.fastq.gz,${DATA_DIR}/HI.4112.002.D710---D503.X21/HI.4112.002.D710---D503.X21_R1_paired.fastq.gz,${DATA_DIR}/HI.4112.002.D711---D501.X30/HI.4112.002.D711---D501.X30_R1_paired.fastq.gz,${DATA_DIR}/HI.4254.008.Index_15.TB2/HI.4254.008.Index_15.TB2_R1_paired.fastq.gz,${DATA_DIR}/HI.4254.008.Index_7.TB9/HI.4254.008.Index_7.TB9_R1_paired.fastq.gz,${DATA_DIR}/SRR1039667_sample123/SRR1039667_sample123_R1_paired_readIDModif.fastq.gz,${DATA_DIR}/SRR1041217_sample144/SRR1041217_sample144_R1_paired_readIDModif.fastq.gz"
RIGHT="${DATA_DIR}/HI.4112.001.D707---D506.X4/HI.4112.001.D707---D506.X4_R2_paired.fastq.gz,${DATA_DIR}/HI.4112.001.D707---D507.X6/HI.4112.001.D707---D507.X6_R2_paired.fastq.gz,${DATA_DIR}/HI.4112.001.D708---D504.X13/HI.4112.001.D708---D504.X13_R2_paired.fastq.gz,${DATA_DIR}/HI.4112.002.D710---D502.X19/HI.4112.002.D710---D502.X19_R2_paired.fastq.gz,${DATA_DIR}/HI.4112.002.D710---D503.X21/HI.4112.002.D710---D503.X21_R2_paired.fastq.gz,${DATA_DIR}/HI.4112.002.D711---D501.X30/HI.4112.002.D711---D501.X30_R2_paired.fastq.gz,${DATA_DIR}/HI.4254.008.Index_15.TB2/HI.4254.008.Index_15.TB2_R2_paired.fastq.gz,${DATA_DIR}/HI.4254.008.Index_7.TB9/HI.4254.008.Index_7.TB9_R2_paired.fastq.gz,${DATA_DIR}/SRR1039667_sample123/SRR1039667_sample123_R2_paired_readIDModif.fastq.gz,${DATA_DIR}/SRR1041217_sample144/SRR1041217_sample144_R2_paired_readIDModif.fastq.gz" 
NB_CPU=24
MAX_MEM="100G"
ADD_PARAMS=""

#Running Trinity
mkdir -p $WORKING_DIRECTORY

echo "Running Trinity version ${VERSION} on ${DATA_DIR} files..."

#Sourcing java 1.8
source /usr/local/genome2/envs/java-1.8-activate

time $TRINITY_EXEC --seqType $SEQ_TYPE --max_memory $MAX_MEM --left $LEFT --right $RIGHT  --CPU $NB_CPU $ADD_PARAMS --output $WORKING_DIRECTORY --verbose  

echo "Running Trinity version ${VERSION} on ${DATA_DIR} files done."

#If run failed execute the failed commands (trinity log)
#bash /scratch/externe/ifremer/pauffret/pinctada_transcriptome_assembly/results/assembly_trinity_norm_10samples_010117/FailedCommands 

#failed command 13.07.17
#/usr/local/genome2/trinityrnaseq-2.4.0/trinity-plugins/parafly/bin/ParaFly -c ${WORKING_DIRECTORY}/recursive_trinity.cmds -CPU 16 -v


