#!/bin/bash
#$ -S /bin/bash
#$ -V
#$ -cwd
#$ -M pauline.auffret@ifremer.fr
#$ -m bea
#$ -q short.q
#$ -pe thread 16
#$ -e /projet/externe/ifremer/pauffret/pinctada_transcriptome_assembly/archives/log/cluster_cdhit-est
#$ -o /projet/externe/ifremer/pauffret/pinctada_transcriptome_assembly/archives/log/cluster_cdhit-est

#Global variables
WORKING_DIRECTORY=/scratch/externe/ifremer/pauffret/pinctada_transcriptome_assembly/results
RESULTS_DIR=/scratch/externe/ifremer/pauffret/pinctada_transcriptome_assembly/results/filter_low_expression
ASSEMBLY=/scratch/externe/ifremer/pauffret/pinctada_transcriptome_assembly/results/Trinity.fasta_brut_011017.predict_orf_m100_corresponding_transcripts_matrix.TPM.not_cross_norm_per_sample_filter_low_expr_0.5_highest_iso_only/Trinity.fasta_brut_011017.predict_orf_m100_corresponding_transcripts_matrix.TPM.not_cross_norm_per_sample_filter_low_expr_0.5_highest_iso_only_filter_low_expression_transcripts
TRINITY_UTIL_DIR=/usr/local/genome2/trinityrnaseq-2.4.0/util
LOG_DIR=/projet/externe/ifremer/pauffret/pinctada_transcriptome_assembly/archives/log/cluster_cdhit-est


CDHIT=/usr/local/genome2/cd-hit/cd-hit-est
CLUSTER_THRESHOLD="0.9"

NBCPU="16"

TAG="${ASSEMBLY##*/}.cluster${CLUSTER_THRESHOLD}_cdhit-est"

mkdir -p ${WORKING_DIRECTORY}/${TAG}

cd ${WORKING_DIRECTORY}/${TAG}

time $CDHIT -i $ASSEMBLY -c $CLUSTER_THRESHOLD -o ${WORKING_DIRECTORY}/${TAG}/${TAG} -T $NBCPU 

time ${TRINITY_UTIL_DIR}/TrinityStats.pl ${WORKING_DIRECTORY}/${TAG}/${TAG} > ${WORKING_DIRECTORY}/${TAG}_stats.txt 


