#!/bin/bash
#$ -S /bin/bash
#$ -V
#$ -cwd
#$ -M pauline.auffret@ifremer.fr
#$ -m bea
#$ -q short.q
#$ -pe thread 4
#$ -e /projet/externe/ifremer/pauffret/pinctada_transcriptome_assembly/archives/log/create_abundance_matrix
#$ -o /projet/externe/ifremer/pauffret/pinctada_transcriptome_assembly/archives/log/create_abundance_matrix


#Global variables
ASSEMBLY=/scratch/externe/ifremer/pauffret/pinctada_transcriptome_assembly/results/predict_orf/Trinity.fasta_brut_011017.predict_orf_m100/Trinity.fasta.transdecoder_dir/Trinity.fasta_brut_011017.predict_orf_m100_corresponding_transcripts
TAG="${ASSEMBLY##*/}_create_abundance_matrix_per_sample"
WORKING_DIRECTORY=/scratch/externe/ifremer/pauffret/pinctada_transcriptome_assembly/results/${TAG}
DATA_DIR=/scratch/externe/ifremer/pauffret/pinctada_transcriptome_assembly/results/Trinity.fasta_brut_011017.predict_orf_m100_corresponding_transcripts_estimate_abundance_per_sample
sample1=${DATA_DIR}/HI.4112.001.D707---D506.X4.isoforms.results
sample2=${DATA_DIR}/HI.4112.001.D707---D507.X6.isoforms.results
sample3=${DATA_DIR}/HI.4112.001.D708---D504.X13.isoforms.results
sample4=${DATA_DIR}/HI.4112.002.D710---D502.X19.isoforms.results
sample5=${DATA_DIR}/HI.4112.002.D710---D503.X21.isoforms.results
sample6=${DATA_DIR}/HI.4112.002.D711---D501.X30.isoforms.results
sample7=${DATA_DIR}/HI.4254.008.Index_15.TB2.isoforms.results
sample8=${DATA_DIR}/HI.4254.008.Index_7.TB9.isoforms.results
sample9=${DATA_DIR}/SRR1039667_sample123.isoforms.results
sample10=${DATA_DIR}/SRR1041217_sample144.isoforms.results

#Trinity variables 
TRINITY_UTIL_DIR=/usr/local/genome2/trinityrnaseq-2.4.0/util
VERSION="2.4.0"
EST_METHOD="RSEM"

mkdir -p ${WORKING_DIRECTORY}

cd ${WORKING_DIRECTORY}

time ${TRINITY_UTIL_DIR}/abundance_estimates_to_matrix.pl --est_method $EST_METHOD \
$sample1 $sample2 $sample3 $sample4 $sample5 $sample6 $sample7 $sample8 $sample9 $sample10

