#!/bin/bash
#$ -S /bin/bash
#$ -V
#$ -cwd
#$ -M pauline.auffret@ifremer.fr
#$ -m bea
#$ -q long.q
#$ -e /projet/externe/ifremer/pauffret/pinctada_transcriptome_assembly/archives/log/filter_low_expression
#$ -o /projet/externe/ifremer/pauffret/pinctada_transcriptome_assembly/archives/log/filter_low_expression

#Global variables
WORKING_DIRECTORY=/scratch/externe/ifremer/pauffret/pinctada_transcriptome_assembly/results
ASSEMBLY=/scratch/externe/ifremer/pauffret/pinctada_transcriptome_assembly/results/predict_orf/Trinity.fasta_brut_011017.predict_orf_m100/Trinity.fasta.transdecoder_dir/Trinity.fasta_brut_011017.predict_orf_m100_corresponding_transcripts
LOG_DIR=/projet/externe/ifremer/pauffret/pinctada_transcriptome_assembly/archives/log/filter_low_expression
MATRIX=/scratch/externe/ifremer/pauffret/pinctada_transcriptome_assembly/results/Trinity.fasta_brut_011017.predict_orf_m100_corresponding_transcripts_create_abundance_matrix_per_sample/matrix.TPM.not_cross_norm

#Trinity variables
TRINITY_UTIL_DIR=/usr/local/genome2/trinityrnaseq-2.4.0/util
MIN_EXPR=0.5

TAG="${ASSEMBLY##*/}_${MATRIX##*/}_per_sample_filter_low_expr_${MIN_EXPR}_highest_iso_only"
OUTPUT=${WORKING_DIRECTORY}/${TAG}/${TAG}_filter_low_expression_transcripts

mkdir -p $WORKING_DIRECTORY/${TAG}

cd $WORKING_DIRECTORY/${TAG}

time ${TRINITY_UTIL_DIR}/filter_low_expr_transcripts.pl --transcripts $ASSEMBLY --matrix $MATRIX --highest_iso_only --min_expr_any $MIN_EXPR --trinity_mode > $OUTPUT

time ${TRINITY_UTIL_DIR}/TrinityStats.pl ${OUTPUT} > ${WORKING_DIRECTORY}/${TAG}/${TAG}_stats.txt


