#!/bin/bash
#$ -S /bin/bash
#$ -V
#$ -cwd
#$ -M pauline.auffret@ifremer.fr
#$ -m bea
#$ -q short.q
#$ -pe thread 8
#$ -e /projet/externe/ifremer/pauffret/pinctada_transcriptome_assembly/archives/log/trimming_trimmomatic
#$ -o /projet/externe/ifremer/pauffret/pinctada_transcriptome_assembly/archives/log/trimming_trimmomatic

#Global variables
WORKING_DIRECTORY=/scratch/externe/ifremer/pauffret/pinctada_transcriptome_assembly/results

#Trimmomatic variables
NCPU=8
TRIMMOMATIC_JAR=/usr/local/genome2/Trimmomatic-0.36/trimmomatic-0.36.jar
ADAPTERS=/usr/local/genome2/Trimmomatic-0.36/adapters/TruSeq3-PE.fa

#FastQC variables
FASTQC_EXEC=/usr/local/genome2/FastQC-v0.11.5/fastqc

#Getting fastq files names
FILE_R1=$(ls *_R1.fastq.gz)
FILE_R2=$(ls *_R2.fastq.gz)

#Running Trimmomatic
echo "Running Trimmomatic on ${FILE_R1%_R1*} file..."
time java -Xmx40G -jar $TRIMMOMATIC_JAR PE \
	-threads $NCPU \
	-phred33 \
        $FILE_R1 \
        $FILE_R2 \
        $WORKING_DIRECTORY/${FILE_R1%.fastq.gz*}_paired.fastq.gz \
        $WORKING_DIRECTORY/${FILE_R1%.fastq.gz*}_single.fastq.gz \
        $WORKING_DIRECTORY/${FILE_R2%.fastq.gz*}_paired.fastq.gz \
        $WORKING_DIRECTORY/${FILE_R2%.fastq.gz*}_single.fastq.gz \
        ILLUMINACLIP:$ADAPTERS:2:20:7 \
        LEADING:26 \
        TRAILING:26 \
        SLIDINGWINDOW:30:30 \
	MINLEN:40
echo "Running Trimmomatic on ${FILE_R1%%_R1*} file done."


#Running Fastqc on trimmed reads
echo "Running FastQC  on ${FILE_R1%_R1*} file..."
mkdir -p $WORKING_DIRECTORY/fastqc_trimmed_reads
time $FASTQC_EXEC $WORKING_DIRECTORY/${FILE_R1%_R1*}*_paired.fastq.gz -o $WORKING_DIRECTORY/fastqc_trimmed_reads/
echo "Running FastQC  on ${FILE_R1%_R1*} done."


